### ISSUE TITLE
Global hotkey with additional toast notification

### ISSUE THREAD

**Issue by Semitalis** [LordJZ/MicStatus#1]
First of all: Great tool, thanks! 👍 

Second: I would like to have some additional features, if you agree.

1) Add a global hotkey to switch the state, e.g. map **APPCOMMAND_LAUNCH_MAIL** to **APPCOMMAND_MICROPHONE_VOLUME_MUTE** as done here:
https://www.reddit.com/r/Windows10/comments/97bzbn/mute_mic_with_hotkeys/e47ohry/

2) Could you also add a windows 10 toast notification, that will be displayed whenever the user is in fullscreen mode (e.g. playing a game) and states wether the mic is currently muted/unmuted?

**Comment by LordJZ** [comment]
Hi @Semitalis,

As far as I understand, the one-liner from reddit is a fully-functional mic toggler? If so, that's great!

It seems to me that if additional functionality is required, like Windows 10 toasts (awesome idea btw!), it should be added to the reddit script, not this app. This app and the PS script are very different in purpose: the script sends a mic toggle message, while my app integrates with Corsair's CUE to provide key bindings and status indication. In other words, this app is a "backend" of a hardware button on the desk that you click, and it lights up in different colors to display different mic states. You can think of it as of a CUE add-on, not a standalone application.

Let me know if this makes sense.

Thanks, and sorry for the late response.

**Comment by Semitalis** [comment]
Thanks, and also sorry for my late response! :-)

I agree with what you said and since I was still in need of what I described for this issue, I went ahead and created my own little project, just in case somebody wonders and wants something similar as I do:
https://github.com/Semitalis/MicTools/

Hope it's OK with you, that I link to it here.

We can also close this issue up.
